on:
  pull_request:
    branches:
      - "dev"
      - "stage"
      - "prod"
jobs:
  build-deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      # sam build 
      - run: sam build --use-container

# Run Unit tests- Specify unit tests here 

# sam deploy
      - if: github.ref == 'refs/heads/dev'
        run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name dev-stack
      - if: github.ref == 'refs/heads/stage'
        run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name stage-stack
      - if: github.ref == 'refs/heads/prod'
        run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name prod-stack
